# eslint-disable yaml/plain-scalar
shellEmulator: true

# eslint-disable-next-line pnpm/yaml-enforce-settings
trustPolicy: 'off'

packages:
  - 'packages/*'

patchedDependencies:
  unplugin-vue-components@30.0.0: patches/unplugin-vue-components.patch

onlyBuiltDependencies:
  - esbuild
  - json-editor-vue
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
