minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - '@iconify/json@2.2.534'
# eslint-disable-next-line pnpm/yaml-enforce-settings
trustPolicy: off
shellEmulator: true

packages:
  - 'packages/*'

allowBuilds:
  core-js: true
  es5-ext: true
  esbuild: true
  json-editor-vue: true
  simple-git-hooks: true
  typeit: true
  vue-demi: true

onlyBuiltDependencies:
  - esbuild
  - json-editor-vue
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
