shellEmulator: true

# eslint-disable-next-line pnpm/yaml-enforce-settings
trustPolicy: off

packages:
  - 'packages/*'

onlyBuiltDependencies:
  - esbuild
  - json-editor-vue
  - simple-git-hooks
  - unrs-resolver
  - vue-demi

allowBuilds:
  core-js: true
  es5-ext: true
  esbuild: true
  json-editor-vue: true
  simple-git-hooks: true
  typeit: true
  vue-demi: true
