/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/403': RouteRecordInfo<
      '/403',
      '/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/500': RouteRecordInfo<
      '/500',
      '/500',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/document': RouteRecordInfo<
      '/document',
      '/document',
      Record<never, never>,
      Record<never, never>,
      | '/document/naive'
      | '/document/unocss'
      | '/document/vite'
      | '/document/vue'
    >,
    '/document/naive': RouteRecordInfo<
      '/document/naive',
      '/document/naive',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/document/unocss': RouteRecordInfo<
      '/document/unocss',
      '/document/unocss',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/document/vite': RouteRecordInfo<
      '/document/vite',
      '/document/vite',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/document/vue': RouteRecordInfo<
      '/document/vue',
      '/document/vue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/function': RouteRecordInfo<
      '/function',
      '/function',
      Record<never, never>,
      Record<never, never>,
      | '/function/hide-child'
      | '/function/hide-child/one'
      | '/function/hide-child/three'
      | '/function/hide-child/two'
    >,
    '/function/hide-child': RouteRecordInfo<
      '/function/hide-child',
      '/function/hide-child',
      Record<never, never>,
      Record<never, never>,
      | '/function/hide-child/one'
      | '/function/hide-child/three'
      | '/function/hide-child/two'
    >,
    '/function/hide-child/one': RouteRecordInfo<
      '/function/hide-child/one',
      '/function/hide-child/one',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/function/hide-child/three': RouteRecordInfo<
      '/function/hide-child/three',
      '/function/hide-child/three',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/function/hide-child/two': RouteRecordInfo<
      '/function/hide-child/two',
      '/function/hide-child/two',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home': RouteRecordInfo<
      '/home',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login/:module(pwd-login|code-login|register|reset-pwd)?',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manage': RouteRecordInfo<
      '/manage',
      '/manage',
      Record<never, never>,
      Record<never, never>,
      | '/manage/role'
      | '/manage/user'
      | '/manage/user-detail.[id]'
    >,
    '/manage/role': RouteRecordInfo<
      '/manage/role',
      '/manage/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manage/user': RouteRecordInfo<
      '/manage/user',
      '/manage/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manage/user-detail.[id]': RouteRecordInfo<
      '/manage/user-detail.[id]',
      '/manage/user-detail/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/multi-menu': RouteRecordInfo<
      '/multi-menu',
      '/multi-menu',
      Record<never, never>,
      Record<never, never>,
      | '/multi-menu/first'
      | '/multi-menu/first/child'
      | '/multi-menu/second'
      | '/multi-menu/second/child'
      | '/multi-menu/second/child/home'
    >,
    '/multi-menu/first': RouteRecordInfo<
      '/multi-menu/first',
      '/multi-menu/first',
      Record<never, never>,
      Record<never, never>,
      | '/multi-menu/first/child'
    >,
    '/multi-menu/first/child': RouteRecordInfo<
      '/multi-menu/first/child',
      '/multi-menu/first/child',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/multi-menu/second': RouteRecordInfo<
      '/multi-menu/second',
      '/multi-menu/second',
      Record<never, never>,
      Record<never, never>,
      | '/multi-menu/second/child'
      | '/multi-menu/second/child/home'
    >,
    '/multi-menu/second/child': RouteRecordInfo<
      '/multi-menu/second/child',
      '/multi-menu/second/child',
      Record<never, never>,
      Record<never, never>,
      | '/multi-menu/second/child/home'
    >,
    '/multi-menu/second/child/home': RouteRecordInfo<
      '/multi-menu/second/child/home',
      '/multi-menu/second/child/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin': RouteRecordInfo<
      '/plugin',
      '/plugin',
      Record<never, never>,
      Record<never, never>,
      | '/plugin/audio'
      | '/plugin/charts'
      | '/plugin/charts/antv'
      | '/plugin/charts/d3'
      | '/plugin/charts/echarts'
      | '/plugin/charts/vchart'
      | '/plugin/copy'
      | '/plugin/excel'
      | '/plugin/flow'
      | '/plugin/flow/vue-flow'
      | '/plugin/gantt'
      | '/plugin/gantt/dhtmlx'
      | '/plugin/gantt/vtable'
      | '/plugin/guide'
      | '/plugin/icon'
      | '/plugin/json'
      | '/plugin/json/json-editor-vue'
      | '/plugin/json/vue-json-pretty'
      | '/plugin/map'
      | '/plugin/map/google'
      | '/plugin/pdf'
      | '/plugin/pdf/html'
      | '/plugin/pdf/link'
      | '/plugin/signature'
      | '/plugin/swiper'
      | '/plugin/tables'
      | '/plugin/tables/ag-grid'
      | '/plugin/tables/vtable'
      | '/plugin/typeit'
      | '/plugin/video'
    >,
    '/plugin/audio': RouteRecordInfo<
      '/plugin/audio',
      '/plugin/audio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/charts': RouteRecordInfo<
      '/plugin/charts',
      '/plugin/charts',
      Record<never, never>,
      Record<never, never>,
      | '/plugin/charts/antv'
      | '/plugin/charts/d3'
      | '/plugin/charts/echarts'
      | '/plugin/charts/vchart'
    >,
    '/plugin/charts/antv': RouteRecordInfo<
      '/plugin/charts/antv',
      '/plugin/charts/antv',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/charts/d3': RouteRecordInfo<
      '/plugin/charts/d3',
      '/plugin/charts/d3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/charts/echarts': RouteRecordInfo<
      '/plugin/charts/echarts',
      '/plugin/charts/echarts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/charts/vchart': RouteRecordInfo<
      '/plugin/charts/vchart',
      '/plugin/charts/vchart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/copy': RouteRecordInfo<
      '/plugin/copy',
      '/plugin/copy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/excel': RouteRecordInfo<
      '/plugin/excel',
      '/plugin/excel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/flow': RouteRecordInfo<
      '/plugin/flow',
      '/plugin/flow',
      Record<never, never>,
      Record<never, never>,
      | '/plugin/flow/vue-flow'
    >,
    '/plugin/flow/vue-flow': RouteRecordInfo<
      '/plugin/flow/vue-flow',
      '/plugin/flow/vue-flow',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/gantt': RouteRecordInfo<
      '/plugin/gantt',
      '/plugin/gantt',
      Record<never, never>,
      Record<never, never>,
      | '/plugin/gantt/dhtmlx'
      | '/plugin/gantt/vtable'
    >,
    '/plugin/gantt/dhtmlx': RouteRecordInfo<
      '/plugin/gantt/dhtmlx',
      '/plugin/gantt/dhtmlx',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/gantt/vtable': RouteRecordInfo<
      '/plugin/gantt/vtable',
      '/plugin/gantt/vtable',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/guide': RouteRecordInfo<
      '/plugin/guide',
      '/plugin/guide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/icon': RouteRecordInfo<
      '/plugin/icon',
      '/plugin/icon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/json': RouteRecordInfo<
      '/plugin/json',
      '/plugin/json',
      Record<never, never>,
      Record<never, never>,
      | '/plugin/json/json-editor-vue'
      | '/plugin/json/vue-json-pretty'
    >,
    '/plugin/json/json-editor-vue': RouteRecordInfo<
      '/plugin/json/json-editor-vue',
      '/plugin/json/json-editor-vue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/json/vue-json-pretty': RouteRecordInfo<
      '/plugin/json/vue-json-pretty',
      '/plugin/json/vue-json-pretty',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/map': RouteRecordInfo<
      '/plugin/map',
      '/plugin/map',
      Record<never, never>,
      Record<never, never>,
      | '/plugin/map/google'
    >,
    '/plugin/map/google': RouteRecordInfo<
      '/plugin/map/google',
      '/plugin/map/google',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/pdf': RouteRecordInfo<
      '/plugin/pdf',
      '/plugin/pdf',
      Record<never, never>,
      Record<never, never>,
      | '/plugin/pdf/html'
      | '/plugin/pdf/link'
    >,
    '/plugin/pdf/html': RouteRecordInfo<
      '/plugin/pdf/html',
      '/plugin/pdf/html',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/pdf/link': RouteRecordInfo<
      '/plugin/pdf/link',
      '/plugin/pdf/link',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/signature': RouteRecordInfo<
      '/plugin/signature',
      '/plugin/signature',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/swiper': RouteRecordInfo<
      '/plugin/swiper',
      '/plugin/swiper',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/tables': RouteRecordInfo<
      '/plugin/tables',
      '/plugin/tables',
      Record<never, never>,
      Record<never, never>,
      | '/plugin/tables/ag-grid'
      | '/plugin/tables/vtable'
    >,
    '/plugin/tables/ag-grid': RouteRecordInfo<
      '/plugin/tables/ag-grid',
      '/plugin/tables/ag-grid',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/tables/vtable': RouteRecordInfo<
      '/plugin/tables/vtable',
      '/plugin/tables/vtable',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/typeit': RouteRecordInfo<
      '/plugin/typeit',
      '/plugin/typeit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugin/video': RouteRecordInfo<
      '/plugin/video',
      '/plugin/video',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user-center': RouteRecordInfo<
      '/user-center',
      '/user-center',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/403.vue': {
      routes:
        | '/403'
      views:
        | never
    }
    'src/pages/404.vue': {
      routes:
        | '/404'
      views:
        | never
    }
    'src/pages/500.vue': {
      routes:
        | '/500'
      views:
        | never
    }
    'src/pages/about.vue': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/pages/document.vue': {
      routes:
        | '/document'
        | '/document/naive'
        | '/document/unocss'
        | '/document/vite'
        | '/document/vue'
      views:
        | 'default'
    }
    'src/pages/document/naive.vue': {
      routes:
        | '/document/naive'
      views:
        | never
    }
    'src/pages/document/unocss.vue': {
      routes:
        | '/document/unocss'
      views:
        | never
    }
    'src/pages/document/vite.vue': {
      routes:
        | '/document/vite'
      views:
        | never
    }
    'src/pages/document/vue.vue': {
      routes:
        | '/document/vue'
      views:
        | never
    }
    'src/pages/function.vue': {
      routes:
        | '/function'
        | '/function/hide-child'
        | '/function/hide-child/one'
        | '/function/hide-child/three'
        | '/function/hide-child/two'
      views:
        | 'default'
    }
    'src/pages/function/hide-child.vue': {
      routes:
        | '/function/hide-child'
        | '/function/hide-child/one'
        | '/function/hide-child/three'
        | '/function/hide-child/two'
      views:
        | 'default'
    }
    'src/pages/function/hide-child/one.vue': {
      routes:
        | '/function/hide-child/one'
      views:
        | never
    }
    'src/pages/function/hide-child/three.vue': {
      routes:
        | '/function/hide-child/three'
      views:
        | never
    }
    'src/pages/function/hide-child/two.vue': {
      routes:
        | '/function/hide-child/two'
      views:
        | never
    }
    'src/pages/home.vue': {
      routes:
        | '/home'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/manage.vue': {
      routes:
        | '/manage'
        | '/manage/role'
        | '/manage/user'
        | '/manage/user-detail.[id]'
      views:
        | 'default'
    }
    'src/pages/manage/role.vue': {
      routes:
        | '/manage/role'
      views:
        | never
    }
    'src/pages/manage/user.vue': {
      routes:
        | '/manage/user'
      views:
        | never
    }
    'src/pages/manage/user-detail.[id].vue': {
      routes:
        | '/manage/user-detail.[id]'
      views:
        | never
    }
    'src/pages/multi-menu.vue': {
      routes:
        | '/multi-menu'
        | '/multi-menu/first'
        | '/multi-menu/first/child'
        | '/multi-menu/second'
        | '/multi-menu/second/child'
        | '/multi-menu/second/child/home'
      views:
        | 'default'
    }
    'src/pages/multi-menu/first.vue': {
      routes:
        | '/multi-menu/first'
        | '/multi-menu/first/child'
      views:
        | 'default'
    }
    'src/pages/multi-menu/first/child.vue': {
      routes:
        | '/multi-menu/first/child'
      views:
        | never
    }
    'src/pages/multi-menu/second.vue': {
      routes:
        | '/multi-menu/second'
        | '/multi-menu/second/child'
        | '/multi-menu/second/child/home'
      views:
        | 'default'
    }
    'src/pages/multi-menu/second/child.vue': {
      routes:
        | '/multi-menu/second/child'
        | '/multi-menu/second/child/home'
      views:
        | 'default'
    }
    'src/pages/multi-menu/second/child/home.vue': {
      routes:
        | '/multi-menu/second/child/home'
      views:
        | never
    }
    'src/pages/plugin.vue': {
      routes:
        | '/plugin'
        | '/plugin/audio'
        | '/plugin/charts'
        | '/plugin/charts/antv'
        | '/plugin/charts/d3'
        | '/plugin/charts/echarts'
        | '/plugin/charts/vchart'
        | '/plugin/copy'
        | '/plugin/excel'
        | '/plugin/flow'
        | '/plugin/flow/vue-flow'
        | '/plugin/gantt'
        | '/plugin/gantt/dhtmlx'
        | '/plugin/gantt/vtable'
        | '/plugin/guide'
        | '/plugin/icon'
        | '/plugin/json'
        | '/plugin/json/json-editor-vue'
        | '/plugin/json/vue-json-pretty'
        | '/plugin/map'
        | '/plugin/map/google'
        | '/plugin/pdf'
        | '/plugin/pdf/html'
        | '/plugin/pdf/link'
        | '/plugin/signature'
        | '/plugin/swiper'
        | '/plugin/tables'
        | '/plugin/tables/ag-grid'
        | '/plugin/tables/vtable'
        | '/plugin/typeit'
        | '/plugin/video'
      views:
        | 'default'
    }
    'src/pages/plugin/audio.vue': {
      routes:
        | '/plugin/audio'
      views:
        | never
    }
    'src/pages/plugin/charts.vue': {
      routes:
        | '/plugin/charts'
        | '/plugin/charts/antv'
        | '/plugin/charts/d3'
        | '/plugin/charts/echarts'
        | '/plugin/charts/vchart'
      views:
        | 'default'
    }
    'src/pages/plugin/charts/antv.vue': {
      routes:
        | '/plugin/charts/antv'
      views:
        | never
    }
    'src/pages/plugin/charts/d3.vue': {
      routes:
        | '/plugin/charts/d3'
      views:
        | never
    }
    'src/pages/plugin/charts/echarts.vue': {
      routes:
        | '/plugin/charts/echarts'
      views:
        | never
    }
    'src/pages/plugin/charts/vchart.vue': {
      routes:
        | '/plugin/charts/vchart'
      views:
        | never
    }
    'src/pages/plugin/copy.vue': {
      routes:
        | '/plugin/copy'
      views:
        | never
    }
    'src/pages/plugin/excel.vue': {
      routes:
        | '/plugin/excel'
      views:
        | never
    }
    'src/pages/plugin/flow.vue': {
      routes:
        | '/plugin/flow'
        | '/plugin/flow/vue-flow'
      views:
        | 'default'
    }
    'src/pages/plugin/flow/vue-flow.vue': {
      routes:
        | '/plugin/flow/vue-flow'
      views:
        | never
    }
    'src/pages/plugin/gantt.vue': {
      routes:
        | '/plugin/gantt'
        | '/plugin/gantt/dhtmlx'
        | '/plugin/gantt/vtable'
      views:
        | 'default'
    }
    'src/pages/plugin/gantt/dhtmlx.vue': {
      routes:
        | '/plugin/gantt/dhtmlx'
      views:
        | never
    }
    'src/pages/plugin/gantt/vtable.vue': {
      routes:
        | '/plugin/gantt/vtable'
      views:
        | never
    }
    'src/pages/plugin/guide.vue': {
      routes:
        | '/plugin/guide'
      views:
        | never
    }
    'src/pages/plugin/icon.vue': {
      routes:
        | '/plugin/icon'
      views:
        | never
    }
    'src/pages/plugin/json.vue': {
      routes:
        | '/plugin/json'
        | '/plugin/json/json-editor-vue'
        | '/plugin/json/vue-json-pretty'
      views:
        | 'default'
    }
    'src/pages/plugin/json/json-editor-vue.vue': {
      routes:
        | '/plugin/json/json-editor-vue'
      views:
        | never
    }
    'src/pages/plugin/json/vue-json-pretty.vue': {
      routes:
        | '/plugin/json/vue-json-pretty'
      views:
        | never
    }
    'src/pages/plugin/map.vue': {
      routes:
        | '/plugin/map'
        | '/plugin/map/google'
      views:
        | 'default'
    }
    'src/pages/plugin/map/google.vue': {
      routes:
        | '/plugin/map/google'
      views:
        | never
    }
    'src/pages/plugin/pdf.vue': {
      routes:
        | '/plugin/pdf'
        | '/plugin/pdf/html'
        | '/plugin/pdf/link'
      views:
        | 'default'
    }
    'src/pages/plugin/pdf/html.vue': {
      routes:
        | '/plugin/pdf/html'
      views:
        | never
    }
    'src/pages/plugin/pdf/link.vue': {
      routes:
        | '/plugin/pdf/link'
      views:
        | never
    }
    'src/pages/plugin/signature.vue': {
      routes:
        | '/plugin/signature'
      views:
        | never
    }
    'src/pages/plugin/swiper.vue': {
      routes:
        | '/plugin/swiper'
      views:
        | never
    }
    'src/pages/plugin/tables.vue': {
      routes:
        | '/plugin/tables'
        | '/plugin/tables/ag-grid'
        | '/plugin/tables/vtable'
      views:
        | 'default'
    }
    'src/pages/plugin/tables/ag-grid.vue': {
      routes:
        | '/plugin/tables/ag-grid'
      views:
        | never
    }
    'src/pages/plugin/tables/vtable.vue': {
      routes:
        | '/plugin/tables/vtable'
      views:
        | never
    }
    'src/pages/plugin/typeit.vue': {
      routes:
        | '/plugin/typeit'
      views:
        | never
    }
    'src/pages/plugin/video.vue': {
      routes:
        | '/plugin/video'
      views:
        | never
    }
    'src/pages/user-center.vue': {
      routes:
        | '/user-center'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
