/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/403': RouteRecordInfo<'/403', '/403', Record<never, never>, Record<never, never>>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/500': RouteRecordInfo<'/500', '/500', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/document': RouteRecordInfo<'/document', '/document', Record<never, never>, Record<never, never>>,
    '/document/naive': RouteRecordInfo<'/document/naive', '/document/naive', Record<never, never>, Record<never, never>>,
    '/document/unocss': RouteRecordInfo<'/document/unocss', '/document/unocss', Record<never, never>, Record<never, never>>,
    '/document/vite': RouteRecordInfo<'/document/vite', '/document/vite', Record<never, never>, Record<never, never>>,
    '/document/vue': RouteRecordInfo<'/document/vue', '/document/vue', Record<never, never>, Record<never, never>>,
    '/function': RouteRecordInfo<'/function', '/function', Record<never, never>, Record<never, never>>,
    '/function/hide-child': RouteRecordInfo<'/function/hide-child', '/function/hide-child', Record<never, never>, Record<never, never>>,
    '/function/hide-child/one': RouteRecordInfo<'/function/hide-child/one', '/function/hide-child/one', Record<never, never>, Record<never, never>>,
    '/function/hide-child/three': RouteRecordInfo<'/function/hide-child/three', '/function/hide-child/three', Record<never, never>, Record<never, never>>,
    '/function/hide-child/two': RouteRecordInfo<'/function/hide-child/two', '/function/hide-child/two', Record<never, never>, Record<never, never>>,
    '/function/multi-tab': RouteRecordInfo<'/function/multi-tab', '/function/multi-tab', Record<never, never>, Record<never, never>>,
    '/function/request': RouteRecordInfo<'/function/request', '/function/request', Record<never, never>, Record<never, never>>,
    '/function/tab': RouteRecordInfo<'/function/tab', '/function/tab', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login/:module(pwd-login|code-login|register|reset-pwd)?', Record<never, never>, Record<never, never>>,
    '/manage': RouteRecordInfo<'/manage', '/manage', Record<never, never>, Record<never, never>>,
    '/manage/role': RouteRecordInfo<'/manage/role', '/manage/role', Record<never, never>, Record<never, never>>,
    '/manage/user': RouteRecordInfo<'/manage/user', '/manage/user', Record<never, never>, Record<never, never>>,
    '/manage/user-detail.[id]': RouteRecordInfo<'/manage/user-detail.[id]', '/manage/user-detail/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/multi-menu': RouteRecordInfo<'/multi-menu', '/multi-menu', Record<never, never>, Record<never, never>>,
    '/multi-menu/first': RouteRecordInfo<'/multi-menu/first', '/multi-menu/first', Record<never, never>, Record<never, never>>,
    '/multi-menu/first/child': RouteRecordInfo<'/multi-menu/first/child', '/multi-menu/first/child', Record<never, never>, Record<never, never>>,
    '/multi-menu/second': RouteRecordInfo<'/multi-menu/second', '/multi-menu/second', Record<never, never>, Record<never, never>>,
    '/multi-menu/second/child': RouteRecordInfo<'/multi-menu/second/child', '/multi-menu/second/child', Record<never, never>, Record<never, never>>,
    '/multi-menu/second/child/home': RouteRecordInfo<'/multi-menu/second/child/home', '/multi-menu/second/child/home', Record<never, never>, Record<never, never>>,
    '/plugin': RouteRecordInfo<'/plugin', '/plugin', Record<never, never>, Record<never, never>>,
    '/plugin/charts': RouteRecordInfo<'/plugin/charts', '/plugin/charts', Record<never, never>, Record<never, never>>,
    '/plugin/charts/antv': RouteRecordInfo<'/plugin/charts/antv', '/plugin/charts/antv', Record<never, never>, Record<never, never>>,
    '/plugin/charts/echarts': RouteRecordInfo<'/plugin/charts/echarts', '/plugin/charts/echarts', Record<never, never>, Record<never, never>>,
    '/plugin/charts/vchart': RouteRecordInfo<'/plugin/charts/vchart', '/plugin/charts/vchart', Record<never, never>, Record<never, never>>,
    '/plugin/copy': RouteRecordInfo<'/plugin/copy', '/plugin/copy', Record<never, never>, Record<never, never>>,
    '/plugin/editor': RouteRecordInfo<'/plugin/editor', '/plugin/editor', Record<never, never>, Record<never, never>>,
    '/plugin/editor/markdown': RouteRecordInfo<'/plugin/editor/markdown', '/plugin/editor/markdown', Record<never, never>, Record<never, never>>,
    '/plugin/excel': RouteRecordInfo<'/plugin/excel', '/plugin/excel', Record<never, never>, Record<never, never>>,
    '/plugin/gantt': RouteRecordInfo<'/plugin/gantt', '/plugin/gantt', Record<never, never>, Record<never, never>>,
    '/plugin/gantt/dhtmlx': RouteRecordInfo<'/plugin/gantt/dhtmlx', '/plugin/gantt/dhtmlx', Record<never, never>, Record<never, never>>,
    '/plugin/gantt/vtable': RouteRecordInfo<'/plugin/gantt/vtable', '/plugin/gantt/vtable', Record<never, never>, Record<never, never>>,
    '/plugin/icon': RouteRecordInfo<'/plugin/icon', '/plugin/icon', Record<never, never>, Record<never, never>>,
    '/plugin/pdf': RouteRecordInfo<'/plugin/pdf', '/plugin/pdf', Record<never, never>, Record<never, never>>,
    '/plugin/pdf/html': RouteRecordInfo<'/plugin/pdf/html', '/plugin/pdf/html', Record<never, never>, Record<never, never>>,
    '/plugin/pdf/link': RouteRecordInfo<'/plugin/pdf/link', '/plugin/pdf/link', Record<never, never>, Record<never, never>>,
    '/plugin/signature': RouteRecordInfo<'/plugin/signature', '/plugin/signature', Record<never, never>, Record<never, never>>,
    '/plugin/swiper': RouteRecordInfo<'/plugin/swiper', '/plugin/swiper', Record<never, never>, Record<never, never>>,
    '/plugin/tables': RouteRecordInfo<'/plugin/tables', '/plugin/tables', Record<never, never>, Record<never, never>>,
    '/plugin/tables/vtable': RouteRecordInfo<'/plugin/tables/vtable', '/plugin/tables/vtable', Record<never, never>, Record<never, never>>,
    '/plugin/typeit': RouteRecordInfo<'/plugin/typeit', '/plugin/typeit', Record<never, never>, Record<never, never>>,
    '/plugin/video': RouteRecordInfo<'/plugin/video', '/plugin/video', Record<never, never>, Record<never, never>>,
    '/user-center': RouteRecordInfo<'/user-center', '/user-center', Record<never, never>, Record<never, never>>,
  }
}
