/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/403': RouteRecordInfo<'/403', '/403', Record<never, never>, Record<never, never>>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/500': RouteRecordInfo<'/500', '/500', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/document': RouteRecordInfo<'/document', '/document', Record<never, never>, Record<never, never>>,
    '/document/naive': RouteRecordInfo<'/document/naive', '/document/naive', Record<never, never>, Record<never, never>>,
    '/document/unocss': RouteRecordInfo<'/document/unocss', '/document/unocss', Record<never, never>, Record<never, never>>,
    '/document/vite': RouteRecordInfo<'/document/vite', '/document/vite', Record<never, never>, Record<never, never>>,
    '/document/vue': RouteRecordInfo<'/document/vue', '/document/vue', Record<never, never>, Record<never, never>>,
    '/function': RouteRecordInfo<'/function', '/function', Record<never, never>, Record<never, never>>,
    '/function/hide-child': RouteRecordInfo<'/function/hide-child', '/function/hide-child', Record<never, never>, Record<never, never>>,
    '/function/hide-child/one': RouteRecordInfo<'/function/hide-child/one', '/function/hide-child/one', Record<never, never>, Record<never, never>>,
    '/function/hide-child/three': RouteRecordInfo<'/function/hide-child/three', '/function/hide-child/three', Record<never, never>, Record<never, never>>,
    '/function/hide-child/two': RouteRecordInfo<'/function/hide-child/two', '/function/hide-child/two', Record<never, never>, Record<never, never>>,
    '/function/multi-tab': RouteRecordInfo<'/function/multi-tab', '/function/multi-tab', Record<never, never>, Record<never, never>>,
    '/function/request': RouteRecordInfo<'/function/request', '/function/request', Record<never, never>, Record<never, never>>,
    '/function/tab': RouteRecordInfo<'/function/tab', '/function/tab', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login/:module(pwd-login|code-login|register|reset-pwd)?', Record<never, never>, Record<never, never>>,
    '/plugin': RouteRecordInfo<'/plugin', '/plugin', Record<never, never>, Record<never, never>>,
    '/plugin/barcode': RouteRecordInfo<'/plugin/barcode', '/plugin/barcode', Record<never, never>, Record<never, never>>,
    '/plugin/copy': RouteRecordInfo<'/plugin/copy', '/plugin/copy', Record<never, never>, Record<never, never>>,
    '/plugin/icon': RouteRecordInfo<'/plugin/icon', '/plugin/icon', Record<never, never>, Record<never, never>>,
    '/plugin/pdf': RouteRecordInfo<'/plugin/pdf', '/plugin/pdf', Record<never, never>, Record<never, never>>,
    '/plugin/print': RouteRecordInfo<'/plugin/print', '/plugin/print', Record<never, never>, Record<never, never>>,
    '/plugin/swiper': RouteRecordInfo<'/plugin/swiper', '/plugin/swiper', Record<never, never>, Record<never, never>>,
    '/plugin/typeit': RouteRecordInfo<'/plugin/typeit', '/plugin/typeit', Record<never, never>, Record<never, never>>,
    '/plugin/video': RouteRecordInfo<'/plugin/video', '/plugin/video', Record<never, never>, Record<never, never>>,
    '/user-center': RouteRecordInfo<'/user-center', '/user-center', Record<never, never>, Record<never, never>>,
  }
}
