import 'virtual:svg-icons-register'
import 'uno.css'
import '../assets/css/global.css'
import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import 'tippy.js/dist/tippy.css'
import 'tippy.js/themes/light.css'
